version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: ssh $DROPLET_USER@$DROPLET_IP 'cd $GIT_PROJECT; git checkout master; git pull; npm install; npm run start:production;'
